import { useState } from "react";
import { Download, Search } from "lucide-react";
import { toast } from "sonner";
import api from "../../services/api";
import { CloudMasterSnapshot, LpnTraceEvent } from "../../types/weighing";
import { Button } from "../ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "../ui/card";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import { useAuthStore } from "../../store/authStore";
import { useI18n } from "../../contexts/I18nContext";

type TraceResponse = {
  packageUid: string;
  items: LpnTraceEvent[];
  total: number;
};

function download(name: string, content: string, type: string) {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function CloudLpnTrace() {
  const user = useAuthStore((state) => state.user);
  const { t } = useI18n();
  const [lpn, setLpn] = useState("");
  const [result, setResult] = useState<TraceResponse | null>(null);
  const [masters, setMasters] = useState<CloudMasterSnapshot | null>(null);
  const [loading, setLoading] = useState(false);

  const search = async () => {
    const value = lpn.trim().toUpperCase();
    if (!value) return;
    setLoading(true);
    try {
      const [trace, master] = await Promise.all([
        api.get<TraceResponse>("/cloud/trace", {
          params: { packageUid: value, limit: 500 },
        }),
        api.get<CloudMasterSnapshot>("/cloud/master-data"),
      ]);
      setResult(trace.data);
      setMasters(master.data);
    } catch (error: any) {
      toast.error(error.response?.data?.message || error.message);
    } finally {
      setLoading(false);
    }
  };

  const currentName = (
    entity: "vendor" | "packaging" | "rm",
    cloudId?: unknown,
  ) => {
    if (!cloudId || !masters) return null;
    if (entity === "vendor") {
      return masters.vendors.find((row) => row.cloudId === cloudId)?.name;
    }
    if (entity === "packaging") {
      return masters.packagings.find((row) => row.cloudId === cloudId)?.name;
    }
    const row = masters.rmCodes.find((item) => item.cloudId === cloudId);
    return row ? `${row.code}${row.name ? ` - ${row.name}` : ""}` : null;
  };

  const exportAudit = async () => {
    if (!result) return;
    const generatedAt = new Date().toISOString();
    const document = {
      reportType: "LPN_AUDIT_TRACE",
      generatedAt,
      generatedBy: user?.username || "unknown",
      packageUid: result.packageUid,
      total: result.total,
      events: result.items,
    };
    const json = JSON.stringify(document, null, 2);
    const csvCell = (value: unknown) =>
      `"${String(value ?? "").replace(/"/g, '""')}"`;
    const csv = [
      [
        "sourceAt",
        "receivedAt",
        "eventType",
        "username",
        "stationId",
        "deviceId",
        "gatewayId",
        "scaleName",
        "packageUid",
      ].join(","),
      ...result.items.map((event) =>
        [
          event.sourceAt,
          event.receivedAt,
          event.eventType,
          event.username,
          event.stationId,
          event.deviceId,
          event.gatewayId,
          event.scaleName,
          event.packageUid,
        ]
          .map(csvCell)
          .join(","),
      ),
    ].join("\n");
    const hash = async (value: string) => {
      const digest = await crypto.subtle.digest(
        "SHA-256",
        new TextEncoder().encode(value),
      );
      return Array.from(new Uint8Array(digest))
        .map((byte) => byte.toString(16).padStart(2, "0"))
        .join("");
    };
    const [jsonHash, csvHash] = await Promise.all([hash(json), hash(csv)]);
    const safeLpn = result.packageUid.replace(/[^A-Za-z0-9_-]/g, "_");
    download(`audit-lpn-${safeLpn}.json`, json, "application/json");
    download(`audit-lpn-${safeLpn}.csv`, csv, "text/csv");
    download(
      `audit-lpn-${safeLpn}.sha256.txt`,
      `${jsonHash}  audit-lpn-${safeLpn}.json\n${csvHash}  audit-lpn-${safeLpn}.csv\nGenerated: ${generatedAt}\nGenerated by: ${user?.username || "unknown"}\n`,
      "text/plain",
    );
  };

  return (
    <Card className="border-[#d7ccc8] bg-[#fff8f0] mb-6">
      <CardHeader>
        <CardTitle className="text-base">{t("cloudLpnTrace")}</CardTitle>
        <CardDescription>{t("cloudLpnTraceHint")}</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex flex-wrap items-end gap-2">
          <div className="space-y-1 min-w-[260px]">
            <Label>LPN</Label>
            <Input
              value={lpn}
              onChange={(event) => setLpn(event.target.value)}
              onKeyDown={(event) => event.key === "Enter" && void search()}
              placeholder="Contoh: LPN/2026/0001"
            />
          </div>
          <Button onClick={() => void search()} disabled={loading}>
            <Search className="w-4 h-4 mr-2" />
            {t("searchTracking")}
          </Button>
          {result && (
            <Button variant="outline" onClick={() => void exportAudit()}>
              <Download className="w-4 h-4 mr-2" />
              {t("exportAuditEvidence")}
            </Button>
          )}
        </div>

        {result && (
          <div className="space-y-3">
            <p className="text-sm text-[#5d4037]">
              {result.total} event untuk{" "}
              <span className="font-mono font-semibold">
                {result.packageUid}
              </span>
            </p>
            {result.items.map((event) => {
              const payload = event.payload || {};
              const vendorCurrent = currentName(
                "vendor",
                payload.vendorCloudId,
              );
              const packagingCurrent = currentName(
                "packaging",
                payload.packagingCloudId,
              );
              const rmCurrent = currentName("rm", payload.rmCodeCloudId);
              return (
                <div
                  key={event.id}
                  className="border-l-4 border-[#8d6e63] bg-white rounded-r-lg p-4"
                >
                  <div className="flex flex-wrap justify-between gap-2">
                    <span className="font-semibold text-[#3e2723]">
                      {event.eventType}
                    </span>
                    <span className="text-xs text-[#8d6e63]">
                      {new Date(event.sourceAt).toLocaleString()}
                    </span>
                  </div>
                  <p className="text-sm mt-1">
                    {event.username} · {event.scaleName || "Tanpa timbangan"} ·
                    station {event.stationId}
                  </p>
                  <p className="text-xs text-[#6d4c41]">
                    device {event.deviceId || "—"} · gateway{" "}
                    {event.gatewayId || "—"}
                  </p>
                  {Boolean(
                    payload.vendorSnapshot ||
                    payload.packagingSnapshot ||
                    payload.rmCodeSnapshot,
                  ) && (
                    <div className="mt-2 text-xs grid md:grid-cols-3 gap-2">
                      <p>
                        Vendor: {String(payload.vendorSnapshot || "—")}{" "}
                        {vendorCurrent &&
                        vendorCurrent !== payload.vendorSnapshot
                          ? `→ ${vendorCurrent}`
                          : ""}
                      </p>
                      <p>
                        Kemasan: {String(payload.packagingSnapshot || "—")}{" "}
                        {packagingCurrent &&
                        packagingCurrent !== payload.packagingSnapshot
                          ? `→ ${packagingCurrent}`
                          : ""}
                      </p>
                      <p>
                        RM: {String(payload.rmCodeSnapshot || "—")}{" "}
                        {rmCurrent && rmCurrent !== payload.rmCodeSnapshot
                          ? `→ ${rmCurrent}`
                          : ""}
                      </p>
                    </div>
                  )}
                </div>
              );
            })}
            {result.items.length === 0 && (
              <p className="text-sm text-center text-[#8d6e63] py-6">
                Belum ada event cloud untuk LPN ini.
              </p>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
